### ISSUE TITLE
In backup addon integrieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/export_cleanup#1]
Meiner meinung nach sollte diese klasse - sobald das hier gut funktioniert und getested ist - direkt im backup addon rein... 

Als separates addon sehe ich das so nicht

**Comment by VIEWSION** [comment]
Jup - würde Sinn machen! Müsste man einfach nur reinkopieren. Zum Testen hab ich es aber erst mal "abgekoppelt".

**Comment by staabm** [comment]
Gerne erst "reifen", danke dafür

**Comment by hirbod** [comment]
Wollte grade das selbe Issue schreiben. Sehe ich auch eher direkt im AddOn

**Comment by AWqxKAWERbXo** [comment]
ich auch, aber mit deutlich weniger Konfigurationsmöglichkeiten.

Mein Vorschlag dazu:
https://github.com/redaxo/redaxo/pull/1254

**Comment by schuer** [comment]
Offenbar inzwischen erledigt.
