### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/export_cleanup#2]
Es gibt offenbar noch kein Release. Wollen wir eins machen?

**Comment by schuer** [comment]
Ping :)
Dann könnte man auch das Küken aus der Projektbeschreibung entfernen.

**Comment by staabm** [comment]
Ist die Funktionalität des addons nicht mittlerweile im core gegeben?

Es werden dort auch addons nach einer gewissen zeit gelöscht. 
Ich meine @alexplusde hatte das gebaut und kennt die details?

**Comment by AWqxKAWERbXo** [comment]
Als Autor steht Matthias Weiß drin. Ich habe Teile dieselbe Idee dazu für den Core gehabt und das gibt's dort auch. Eigentlich ist das hier obsolet imho.

**Comment by schuer** [comment]
Ah, okay. Dann ergänzen wir in der README einen Hinweis, dass die Funktionalität inzwischen im REDAXO-Core ist, und archivieren dann das Repo. In Ordnung, @VIEWSION?

**Comment by staabm** [comment]
Ich habe das addon nicht ausprobiert. Was ich in der aktuellen readme lesen kann was es mitbringt finde ich überschneidungen mit dem core. 

Wenn es für irgendwen einen nutzen/mehrwert hat kann es natürlich gerne in den installer

**Comment by VIEWSION** [comment]
@schuer - gerne. Hab die Core-Version noch gar nicht getestet... aber klar wenn das so ist können wir das Addon hier gerne auf Eis legen.

**Comment by AWqxKAWERbXo** [comment]
@VIEWSION schau dir mal den aktuellen Backup-Cronjob an seit 5.6 glaube ich. Da kann man sagen: nur 1/Monat behalten oder 1/Woche. Und das reicht ja auch imho. Oder gibt es was, das deine Lösung besser kann?
